summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-x86_64/releases/download/2022.09.26/pkg-config-0.29.2-macos-x86_64.tar.xz
bin-sha: 827e20f21839b75de2369c29ebd1bb2a07f25512b29b35c3a4bed56ef65d22c3
