summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-x86_64/releases/download/2022.11.10/pkg-config-0.29.2-macos-x86_64.tar.xz
bin-sha: cffd6fc2294fe3caff02236dc490e55b929b575638ad6aceb616beb05e962db5
